# Generated by Django 3.1 on 2020-10-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiong_text',
            new_name='question_text',
        ),
    ]
